openapi: "3.0.0"
info:
  title: Tshirt store API
  description: This is a online ecom store for Tshirts
  version: 1.1.0
  contact :                                 # For Customer Support
    email: rudbhav.gupta@gmail.com
    # url: "google.com"

# servers:
#   - url: "https://localhost:4000/api/v1"
#     description: for local host - secure
#   - url: "http://localhost:4000/api/v1"
#     description: for local host - regular

servers:
  - url: "{protocol}://localhost:4000/api/{version}"
    description: for local host - secure
    variables:
      version:     # variable 1
        enum:      # enum restrict values to below two only
          - v1     # variable values
          - v2     
        default: v1   #default variable value
      protocol:    # variable 2
        enum:
         - http
         - https
        default: http

components:    
  securitySchemes:      # Authorization 
    cookieAuth:
      type: apiKey
      in: cookie
      name: token      #just for our reference  , it will help later
    BearerAuth:
      type: http
      scheme: bearer